modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "CC BY-SA"

[[mods]]
modId = "vs_marinepropulsion"
version = "${version}"
displayName = "VS Marine Propulsion"
authors = "Daniel366Cobra"
description = '''
Exploring options for Valkyrien Skies watercraft propulsion.
'''
logoFile = "icon.png"

[[dependencies.vs_marinepropulsion]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_marinepropulsion]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_marinepropulsion]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"
